export const firstOne = document.getElementById('selectorOne')
export const twoSecond = document.getElementById('selectorSecond')
export const threeSecond = document.getElementById('selectorThree')
export const fourSecond = document.getElementById('selectorFour')
export const paramentGroup = document.getElementById('paramentsGroup')
export const dopCredit = document.getElementById('dopCredit')

export const btn = document.getElementById('result')
export const btnExcel = document.getElementById('exportExcel')
export const btnSelectGroupAdd = document.getElementById('openPopup')
export const btnSelectGroupRemode = document.getElementById('popupClose')
export const addSubmitZarplata = document.querySelector('.paramentsStavok__btn_addZarplata')
export const addSubmitKi = document.querySelector('.paramentsStavok__btn_addKi')
export const addSubmitElectons = document.querySelector('.paramentsStavok__btn_addElectrons')
export const addSubmitNoRef = document.querySelector('.paramentsStavok__btn_addNoRef')
export const addSubmitStrahovka = document.querySelector('.paramentsStavok__btn_addStrahovka')

export const deleteSubmitZarplata = document.querySelector('.paramentsStavok__btn_deleteZarplata')
export const deleteSubmitKi = document.querySelector('.paramentsStavok__btn_deleteKi')
export const deleteSubmitElectons = document.querySelector('.paramentsStavok__btn_deleteElectrons')
export const deleteSubmitNoRef = document.querySelector('.paramentsStavok__btn_deleteNoRef')
export const deleteSubmitStrahovka = document.querySelector('.paramentsStavok__btn_deleteStrahovka')

export const celsProgram = document.getElementById('selectorOne')
export const credictProduct = document.getElementById('selectorSecond')
export const sumCredit = document.getElementById('razrydSum')
export const costHouse = document.getElementById('razrydSale')
export const timeCredit = document.getElementById('paramentsTime')
export const paramentGroups = document.getElementById('paramentsGroup')
export const zarplataSt = document.getElementById('zarplataSt')
export const kiSt = document.getElementById('kiSt')
export const electronSt = document.getElementById('electronSt')
export const noRefSt = document.getElementById('noRefSt')
export const noStrahovkaSt = document.getElementById('noStrahovkaSt')
export const program = document.getElementById('resultProgram')
export const infoVklad = document.getElementById('infoVklad')

export let monthPayment = document.getElementById('monthPayment')
export let pereplata = document.getElementById('pereplata')
export let resultStavka = document.getElementById('resultStavka')
export let resultProduct = document.getElementById('resultProduct')
export let resultProgramma = document.getElementById('resultProgramma')
export let resultKZ = document.getElementById('resultKZ')  
export let popup = document.getElementById('popupId')
export let table = document.getElementById('paymentScheduleTable')
export const errorTime = document.getElementById('error-time')
export const errorGroup = document.getElementById('error-groupCredit')
export const errorCredit = document.getElementById('error-costCredit')

export const periodOneMin = document.getElementById('periodOneMin')
export const priodOneMax = document.getElementById('priodOneMax')
export const procentOne = document.getElementById('procentOne')
export const periodTwoMin = document.getElementById('periodTwoMin')
export const priodTwoMax = document.getElementById('priodTwoMax')
export const procentTwo = document.getElementById('procentTwo')
export const periodThreeMin = document.getElementById('periodThreeMin')
export const priodThreeMax = document.getElementById('priodThreeMax')
export const procentThree = document.getElementById('procentThree')
export const periodFourMin = document.getElementById('periodFourMin')
export const priodFourMax = document.getElementById('priodFourMax')
export const procentFour = document.getElementById('procentFour')
export const raschet = document.getElementById('raschet')

export const sumOne = document.getElementById('sumOne')
export const sumTwo = document.getElementById('sumTwo')
export const sumThree = document.getElementById('sumThree')
export const sumFour = document.getElementById('sumFour')
export const sumFive = document.getElementById('sumFive')